fixtures:
  repositories:
    "selinux": "https://github.com/camptocamp/puppet-selinux.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "archive": "https://github.com/camptocamp/puppet-archive.git"
  symlinks:
    "shibboleth": "#{source_dir}"
